### ISSUE TITLE
Allow configuration properties (not only default ...)

### ISSUE THREAD

**Issue by mqueb** [spring-cloud/spring-cloud-circuitbreaker#109]
currently:
```
	public Resilience4JCircuitBreakerFactory(
			CircuitBreakerRegistry circuitBreakerRegistry,
			TimeLimiterRegistry timeLimiterRegistry,
			Resilience4jBulkheadProvider bulkheadProvider) {
		this.circuitBreakerRegistry = circuitBreakerRegistry;
		this.timeLimiterRegistry = timeLimiterRegistry;
		this.bulkheadProvider = bulkheadProvider;
		this.defaultConfiguration = id -> new Resilience4JConfigBuilder(id)
				.circuitBreakerConfig(this.circuitBreakerRegistry.getDefaultConfig())
				.timeLimiterConfig(this.timeLimiterRegistry.getDefaultConfig()).build();
	}
```

could be:
```
	public Resilience4JCircuitBreakerFactory(
			CircuitBreakerRegistry circuitBreakerRegistry,
			TimeLimiterRegistry timeLimiterRegistry,
			Resilience4jBulkheadProvider bulkheadProvider) {
		this.circuitBreakerRegistry = circuitBreakerRegistry;
		this.timeLimiterRegistry = timeLimiterRegistry;
		this.bulkheadProvider = bulkheadProvider;
		this.defaultConfiguration = id -> new Resilience4JConfigBuilder(id)
				.circuitBreakerConfig(this.circuitBreakerRegistry.circuitBreaker(id).getCircuitBreakerConfig())
				.timeLimiterConfig(this.timeLimiterRegistry.timeLimiter(id).getTimeLimiterConfig()).build();
	}
```

that way a config like:
```
resilience4j:
  circuitbreaker:
    configs:
      default:
        minimumNumberOfCalls: 5
        failureRateThreshold: 60
        waitDurationInOpenState: 5000
        slowCallDurationThreshold: 2000
      communicationExterne:
        minimumNumberOfCalls: 5
        failureRateThreshold: 70
        waitDurationInOpenState: 7000
        slowCallDurationThreshold: 2500
        ignoreExceptions:
          - com.ffdffd.commons.domaine.exception.CommunicationExterneApiException
    instances:
      envoyerSms:
        baseConfig: communicationExterne
      appelVocal:
        baseConfig: communicationExterne
      envoiCourriel:
        baseConfig: communicationExterne
```

with  
`circuitBreakerFactory.create("envoyerSms")`  i will get my config without code

same pattern for bulkHead
