### ISSUE TITLE
Document How To Customize The ExecutorService

### ISSUE THREAD

**Issue by v-v-y** [spring-cloud/spring-cloud-circuitbreaker#161]
**Describe the bug**
As a developer, I'd like to see tracing context from MDC during executing requests. Now if I enable circuit-breaker context disappears from logs.

**Sample**
Example project: https://github.com/v-v-y/demo

Java: 17
Spring boot: 2.7.6
spring-cloud-starter-circuitbreaker-resilience4j: 2.0.2
spring-cloud-starter-openfeign: 3.1.5

application.yaml
```
spring:
  application:
    name: demo-application
  profiles:
    active: dev
  cloud:
    open-feign:
      client:
        config:
          default:
            loggerLevel: BASIC
feign:
  circuit-breaker:
    enabled: true

resilience4j:
  scheduled:
    executor:
      corePoolSize: 10
      contextPropagators:
        - com.example.demo.MdcContextPropagator
  circuit-breaker:
    configs:
      default:
        slidingWindowType: TIME_BASED
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        slidingWindowSize: 60
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        recordFailurePredicate: com.example.demo.ErrorPredicate
        registerHealthIndicator: true

```

The difference in logs during calling example controller GET /v1/discovery

if feign.circuit-breaker.enabled: true
```
[2022-12-18 14:25:36.569] [pool-2-thread-1] com.example.demo.GoogleClient             []  DEBUG: [GoogleClient#discovery] ---> GET https://docs.googleapis.com/$discovery/rest?version=v1 HTTP/1.1 
[2022-12-18 14:25:37.077] [pool-2-thread-1] com.example.demo.GoogleClient             []  DEBUG: [GoogleClient#discovery] <--- HTTP/1.1 200 OK (506ms) 

```

if feign.circuit-breaker.enabled: false
```
[2022-12-18 14:26:09.812] [http-nio-8080-exec-1] com.example.demo.GoogleClient             [1f143097-3f5e-467d-9038-aa6d511c1895]  DEBUG: [GoogleClient#discovery] ---> GET https://docs.googleapis.com/$discovery/rest?version=v1 HTTP/1.1 
[2022-12-18 14:26:10.333] [http-nio-8080-exec-1] com.example.demo.GoogleClient             [1f143097-3f5e-467d-9038-aa6d511c1895]  DEBUG: [GoogleClient#discovery] <--- HTTP/1.1 200 OK (518ms) 
```

Look like ContextAwareScheduledThreadPoolExecutor created, but never used. I've also tried to provide specific contextPropagator but it didn't help too
