### ISSUE TITLE
Timelimiter metrics stays at 0.0 on successful requests after update to Spring Boot 3

### ISSUE THREAD

**Issue by shellrausch** [spring-cloud/spring-cloud-circuitbreaker#162]
Spring Boot version: 3.0.1
Spring Cloud version: 2022.0.0
Java version: 17

After updating to Spring Boot 3 many of the metrics stays always at 0.0:
```
# HELP resilience4j_timelimiter_calls_total The number of successful calls
# TYPE resilience4j_timelimiter_calls_total counter
resilience4j_timelimiter_calls_total{group="none",kind="successful",name="test",} 0.0
```

My dependencies:
```
dependencies {
    implementation("org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j")
    implementation("org.springframework.cloud:spring-cloud-starter-openfeign")
    implementation("io.micrometer:micrometer-core:1.10.3")
    implementation("io.micrometer:micrometer-registry-prometheus:1.10.3")
    implementation("io.github.resilience4j:resilience4j-micrometer:2.0.2")
    ...
}
```

The config:
```
management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        resilience4j.circuitbreaker.calls: true
```
