### ISSUE TITLE
Retry wait-duration config ignored when specifying wait-duration.seconds = x

### ISSUE THREAD

**Issue by MikeMJ** [spring-cloud/spring-cloud-circuitbreaker#179]
Resilience4j version: 2.0.2

Java version: 21

I'm using Spring Boot 3.2.0 with spring-cloud-starter-circuitbreaker-resilience4j. I've noticed the Retry custom wait duration is ignored and set to default (0.5S) if I configure it in the application.yml file like the following:

```
resilience4j:
  retry:
    configs:
      default:
        enable-exponential-backoff: true
        max-attempts: 8
        wait-duration:
          seconds: 2s
```
But if I change it to

```
resilience4j:
  retry:
    configs:
      default:
        enable-exponential-backoff: true
        max-attempts: 8
        wait-duration: 2s
```
the wait duration is picked from the config
