### ISSUE TITLE
Circuit Breaker Not working as expected on Spring cloud version 2024.0.1

### ISSUE THREAD

**Issue by swetharajshree** [spring-cloud/spring-cloud-circuitbreaker#237]
I was initially using spring cloud version of 2023.0.3 and the circuit breaker pattern was working fine. When the spring cloud version is changed to 2024.0.1 it stopped working. The following are the dependencies we use implementation('org.springframework.cloud:spring-cloud-starter-circuitbreaker-reactor-resilience4j')
implementation('org.springframework.cloud:spring-cloud-starter-gateway')
The spring boot version is 3.4.4
The following is are configuration
```
        - id: check
          uri: http://localhost:8083
          predicates:
            - Path=/check/**
          filters:
            - name: CircuitBreaker
              args:
                name: checkCircuitBreaker
                fallbackUri: forward:/fallback

resilience4j:
  circuitbreaker:
    instances:
      checkCircuitBreaker:
        registerHealthIndicator: true
        minimumNumberOfCalls: 1a
        failureRateThreshold: 1
        slidingWindowSize: 1 
        waitDurationInOpenState: 1s 
        permittedNumberOfCallsInHalfOpenState: 1 
```
We have a controller with the /fallback mapping which routes the request to another service if the check service is not reachable.
Using 2023.0.3 and 2024.0.0 when the request is received if the check service is up it sends the request to the check service and if it is down it forwards to another service. But in 2024.0.1 when the request is received even if the check service is up it doesnt send the request to the check service neither sends the request to the fallback URL.

If we downgrade the spring cloud version it is working as expected. If we remove the circuit breaker pattern then the request is sent to check service if the service is up. So you please help us with this
