### ISSUE TITLE
Shouldn't resilience4j's time limiter respect Feign timeouts?

### ISSUE THREAD

**Issue by eduardo-bueno-ifood** [spring-cloud/spring-cloud-circuitbreaker#90]
Working with OpenFeign, Resilience4j completely disregards any connectTimeout/readTimeout configured in a client. I have tested with specific clients as well as `feign.client.config.default`. It would be nice to have things working in tandem.

Additionally, Resilience4j's documentation is really confusing and I can't find an equivalent of this Hystrix configuration:
```
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
```
I tried it like below but it didn't work. Would appreciate if anyone knows how to tweak the default timeout.
```
resilience4j.timelimiter:
  instances:
    backendA:
      timeoutDuration: 5s
    backendB:
      timeoutDuration: 5s
```
