### ISSUE TITLE
CirciutBreaker/TimeLimiter/Bulkheads should use default Resilience4j properties configuration 

### ISSUE THREAD

**Issue by Ferioney** [spring-cloud/spring-cloud-circuitbreaker#94]
Spring Boot Resilience4j provides default properties configuration:
```
resilience4j.circuitbreaker:
    configs:
        default:
            slidingWindowSize: 100
            permittedNumberOfCallsInHalfOpenState: 10
```
To my mind, this configuration should be used as default instead of `CircuitBreakerConfig.ofDefaults()`.
